### ISSUE TITLE
Broken build on Ubuntu 20.04 (565d1e27d75a51223b8f48b618ec913320f836e0)

### ISSUE THREAD

**Issue by skmp** [FEX-Emu/FEX#1457]
Tested commit: 565d1e27d75a51223b8f48b618ec913320f836e0
This seems unrelated to the previous problem I was having

```
In file included from ../Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp:1:
In file included from ../Source/Tests/LinuxSyscalls/x32/Ioctl/drm.h:5:
In file included from ../Source/Tests/LinuxSyscalls/x32/Types.h:12:
In file included from /usr/include/x86_64-linux-gnu/asm/ipcbuf.h:1:
/include/asm-generic/ipcbuf.h:21:2: error: unknown type name '__kernel_key_t'
        __kernel_key_t          key;
        ^
/include/asm-generic/ipcbuf.h:22:2: error: unknown type name '__kernel_uid32_t'
        __kernel_uid32_t        uid;
        ^
/include/asm-generic/ipcbuf.h:23:2: error: unknown type name '__kernel_gid32_t'
        __kernel_gid32_t        gid;
        ^
/include/asm-generic/ipcbuf.h:24:2: error: unknown type name '__kernel_uid32_t'
        __kernel_uid32_t        cuid;
        ^
/include/asm-generic/ipcbuf.h:25:2: error: unknown type name '__kernel_gid32_t'
        __kernel_gid32_t        cgid;
        ^
/include/asm-generic/ipcbuf.h:26:2: error: unknown type name '__kernel_mode_t'
        __kernel_mode_t         mode;
        ^
/include/asm-generic/ipcbuf.h:28:35: error: use of undeclared identifier '__kernel_mode_t'
        unsigned char           __pad1[4 - sizeof(__kernel_mode_t)];
                                                  ^
/include/asm-generic/ipcbuf.h:31:2: error: unknown type name '__kernel_ulong_t'
        __kernel_ulong_t        __unused1;
        ^
/include/asm-generic/ipcbuf.h:32:2: error: unknown type name '__kernel_ulong_t'
        __kernel_ulong_t        __unused2;
        ^
In file included from ../Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp:1:
In file included from ../Source/Tests/LinuxSyscalls/x32/Ioctl/drm.h:5:
In file included from ../Source/Tests/LinuxSyscalls/x32/Types.h:13:
In file included from /usr/include/x86_64-linux-gnu/asm/shmbuf.h:6:
/include/asm-generic/shmbuf.h:29:2: error: unknown type name '__kernel_time_t'
        __kernel_time_t         shm_atime;      /* last attach time */
        ^
/include/asm-generic/shmbuf.h:30:2: error: unknown type name '__kernel_time_t'
        __kernel_time_t         shm_dtime;      /* last detach time */
        ^
/include/asm-generic/shmbuf.h:31:2: error: unknown type name '__kernel_time_t'
        __kernel_time_t         shm_ctime;      /* last change time */
        ^
/include/asm-generic/shmbuf.h:40:2: error: unknown type name '__kernel_pid_t'
        __kernel_pid_t          shm_cpid;       /* pid of creator */
        ^
/include/asm-generic/shmbuf.h:41:2: error: unknown type name '__kernel_pid_t'
        __kernel_pid_t          shm_lpid;       /* pid of last operator */

```

**Comment by skmp** [comment]
Also getting some linking errors, disabling LTO seems to fix those

```
FAILED: Bin/Opt 
: && /usr/bin/clang++  -mcx16 -march=native -O2 -g -DNDEBUG -fno-omit-frame-pointer -flto=thin  -fPIE -pie Source/Tools/CMakeFiles/Opt.dir/Opt.cpp.o  -o Bin/Opt  External/FEXCore/Source/libFEXCore.a  Source/Common/libCommon.a  Source/CommonCore/libCommonCore.a  -lpthread  External/cpp-optparse/libcpp-optparse.a  External/json-maker/libjson-maker.a  External/FEXCore/Source/libFEXCore.a  External/FEXCore/Source/libFEXCore_Base.a  External/fmt/libfmt.a  External/vixl/src/libvixl.a  -ldl  External/xxhash/libxxhash.a  External/tiny-json/libtiny-json.a  -lpthread && :
/usr/bin/ld: error: Failed to link module External/FEXCore/Source/libFEXCore.a.llvm.80876708.jemalloc.c: Expected at most one ThinLTO module per bitcode file
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[7/23] Linking CXX executable Bin/UnitTestGenerator
FAILED: Bin/UnitTestGenerator 
: && /usr/bin/clang++  -mcx16 -march=native -O2 -g -DNDEBUG -fno-omit-frame-pointer -flto=thin  -fPIE -pie Source/Tests/CMakeFiles/UnitTestGenerator.dir/UnitTestGenerator.cpp.o  -o Bin/UnitTestGenerator  External/FEXCore/Source/libFEXCore.a  Source/Common/libCommon.a  Source/CommonCore/libCommonCore.a  -lpthread  External/cpp-optparse/libcpp-optparse.a  External/json-maker/libjson-maker.a  External/FEXCore/Source/libFEXCore.a  External/FEXCore/Source/libFEXCore_Base.a  External/fmt/libfmt.a  External/vixl/src/libvixl.a  -ldl  External/xxhash/libxxhash.a  External/tiny-json/libtiny-json.a  -lpthread && :
/usr/bin/ld: error: Failed to link module External/FEXCore/Source/libFEXCore.a.llvm.80876708.jemalloc.c: Expected at most one ThinLTO module per bitcode file
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[10/23] Building CXX object Source/Tests/LinuxSyscalls/CMakeFiles/LinuxEmulation.dir/x32/IoctlEmulation.cpp.o
```

**Comment by skmp** [comment]
Reverting 45430e9 fixes the build issue
